name: learning_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  get: 4.6.5
  google_fonts: ^3.0.1
  intl: ^0.17.0
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_sliders: ^20.2.49

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
